force-app/main/default/objects/BitForce_Status_Log__c/BitForce_Status_Log__c.object-meta.xml
<CustomObject>
    <label>BitForce Status Log</label>
    <nameField>
        <label>BitForce Status Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BitForce Status Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BitForce_Status_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BitForce_Status_Log__c/fields/MP_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>MP_Payment_Id__c</fullName>
    <label>MP Payment Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BitForce_Status_Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>MP_Payment__c</referenceTo>
    <relationshipLabel>BitForce Status Logs</relationshipLabel>
    <relationshipName>BitForce_Status_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BitForce_Status_Log__c/fields/Status_Details__c.field-meta.xml
<CustomField>
    <fullName>Status_Details__c</fullName>
    <label>Status Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/MP_Payment__c.object-meta.xml
<CustomObject>
    <label>MP Payment</label>
    <nameField>
        <label>MP Payment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MP Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/MercadoPagoSyncBatch.cls
public class MercadoPagoSyncBatch implements Database.Batchable<BitForce_Status_Log__c>, Database.AllowsCallouts{

    private final List<BitForce_Status_Log__c> records;

    public MercadoPagoSyncBatch(List<String> payments, String processName, String endpoint) {
        List<BitForce_Status_Log__c> recs = new List<BitForce_Status_Log__c>();

        for(String p : payments)
            recs.add(new BitForce_Status_Log__c(
                Name = processName,
                Status__c = 'Queued',
                MP_Payment_Id__c = p,
                Endpoint__c = endpoint
            ));

        insert recs;

        this.records = recs;
    }

    public List<BitForce_Status_Log__c> start(DataBase.BatchableContext bc){
        return records;
    }

    public void execute(Database.BatchableContext bc, List<BitForce_Status_Log__c> records){
        BitForce_Status_Log__c rec = records[0];

        try{
            Boolean processed = MercadoPagoNotificationHandler.HandleNotification(rec.MP_Payment_Id__c, 'payment', rec.Endpoint__c);

            if(processed){
                rec.Status__c = 'Done - Success';
            } else{
                rec.Status__c = 'Done - Failed';
            }

            List<MP_Payment__c> payments = [SELECT Id FROM MP_Payment__c WHERE Name = :rec.MP_Payment_Id__c];

            if(payments.size() > 0)
                rec.Payment__c = payments[0].Id;
            else
                rec.Status_Details__c = 'Done - Check Notification Log';

        } catch(Exception ex){
            rec.Status__c = 'Error';
            rec.Status_Details__c = ex.getMessage() + ' - ' + ex.getStackTraceString();
        }

        update rec;
    }

    public void finish(Database.BatchableContext bc){
        System.debug('done');
    }
}