force-app/main/default/objects/Contact/fields/MP_Payer_ID__c.field-meta.xml
<CustomField>
    <fullName>MP_Payer_ID__c</fullName>
    <label>MP Payer ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/MP_Payment__c.object-meta.xml
<CustomObject>
    <label>MP Payment</label>
    <nameField>
        <label>MP Payment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MP Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MP_Payment__c/fields/Card_Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Card_Date_Created__c</fullName>
    <label>Card Date Created</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/Card_Date_Created_DT__c.field-meta.xml
<CustomField>
    <fullName>Card_Date_Created_DT__c</fullName>
    <label>Card Date Created DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/Card_Date_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Card_Date_Last_Updated__c</fullName>
    <label>Card Date Last Updated</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/Card_Date_Last_Updated_DT__c.field-meta.xml
<CustomField>
    <fullName>Card_Date_Last_Updated_DT__c</fullName>
    <label>Card Date Last Updated DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/Date_Approved__c.field-meta.xml
<CustomField>
    <fullName>Date_Approved__c</fullName>
    <label>Date Approved</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/Date_Approved_DT__c.field-meta.xml
<CustomField>
    <fullName>Date_Approved_DT__c</fullName>
    <label>Date Approved DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <label>Date Created</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/Date_Created_DT__c.field-meta.xml
<CustomField>
    <fullName>Date_Created_DT__c</fullName>
    <label>Date Created DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/Date_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Updated__c</fullName>
    <label>Date Last Updated</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/Date_Last_Updated_DT__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Updated_DT__c</fullName>
    <label>Date Last Updated DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Payment__c/fields/MP_Subscription__c.field-meta.xml
<CustomField>
    <fullName>MP_Subscription__c</fullName>
    <label>MP Subscription</label>
    <referenceTo>MP_Subscription__c</referenceTo>
    <relationshipLabel>MP Payments</relationshipLabel>
    <relationshipName>MP_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/MP_Subscription__c.object-meta.xml
<CustomObject>
    <label>MP Subscription</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MP Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Auto_Recurring_End_Date__c.field-meta.xml
<CustomField>
    <fullName>MP_Auto_Recurring_End_Date__c</fullName>
    <label>MP Auto Recurring End Date</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Auto_Recurring_End_Date_DT__c.field-meta.xml
<CustomField>
    <fullName>MP_Auto_Recurring_End_Date_DT__c</fullName>
    <label>MP Auto Recurring End Date DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Auto_Recurring_Frequency_Type__c.field-meta.xml
<CustomField>
    <fullName>MP_Auto_Recurring_Frequency_Type__c</fullName>
    <label>MP Auto Recurring Frequency Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Auto_Recurring_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>MP_Auto_Recurring_Start_Date__c</fullName>
    <label>MP Auto Recurring Start Date</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Auto_Recurring_Start_Date_DT__c.field-meta.xml
<CustomField>
    <fullName>MP_Auto_Recurring_Start_Date_DT__c</fullName>
    <label>MP Auto Recurring Start Date DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Date_Created__c.field-meta.xml
<CustomField>
    <fullName>MP_Date_Created__c</fullName>
    <label>MP Date Created</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Last_Modified_DT__c.field-meta.xml
<CustomField>
    <fullName>MP_Last_Modified_DT__c</fullName>
    <label>MP Last Modified DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Next_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>MP_Next_Installment_Date__c</fullName>
    <label>MP Next Installment Date</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Next_Installment_Date_DT__c.field-meta.xml
<CustomField>
    <fullName>MP_Next_Installment_Date_DT__c</fullName>
    <label>MP Next Installment Date DT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Payer_ID__c.field-meta.xml
<CustomField>
    <fullName>MP_Payer_ID__c</fullName>
    <label>MP Payer ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Subscription_Plan__c.field-meta.xml
<CustomField>
    <fullName>MP_Subscription_Plan__c</fullName>
    <label>MP Subscription Plan</label>
    <referenceTo>MP_Subscription_Plan__c</referenceTo>
    <relationshipLabel>MP Subscriptions</relationshipLabel>
    <relationshipName>MP_Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Summary_Last_Charged_Date__c.field-meta.xml
<CustomField>
    <fullName>MP_Summary_Last_Charged_Date__c</fullName>
    <label>MP Summary Last Charged Date</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MP_Subscription__c/fields/MP_Summary_Last_Charged_Date_DT__c.field-meta.xml
<CustomField>
    <fullName>MP_Summary_Last_Charged_Date_DT__c</fullName>
    <label>MP Summary Last Charged Date DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Subscription_Plan__c/MP_Subscription_Plan__c.object-meta.xml
<CustomObject>
    <description>MercadoPago subscription plans</description>
    <label>MP Subscription Plan</label>
    <nameField>
        <label>MP Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MP Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MP_Subscription_Plan__c/fields/MP_Date_Created_DT__c.field-meta.xml
<CustomField>
    <fullName>MP_Date_Created_DT__c</fullName>
    <label>MP Date Created DT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MP_Subscription_Plan__c/fields/MP_Last_Modified__c.field-meta.xml
<CustomField>
    <fullName>MP_Last_Modified__c</fullName>
    <label>MP Last Modified</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MercadoPagoUtils.cls
global without sharing class MercadoPagoUtils {
    
    @InvocableMethod
    public static List<Results> MercadoPagoUtilities(List<Requests> requests) {
        if (requests[0].action == 'GetPayerData') {
            return GetPayerData(requests);
        } else if (requests[0].action == 'ParsePaymentDates') {
            return ParsePaymentDates(requests);
        } else if (requests[0].action == 'ParseSubscriptionDates') {
            return ParseSubscriptionDates(requests);
        } else if (requests[0].action == 'ParsePlanDates') {
            return ParsePlanDates(requests);
        } else {
            Results res = new Results();
            res.status = false;
            List<Results> resultList = new List<Results>();
            resultList.add(res);
            return resultList;
        }
        
    }
    
    private static List<Results> GetPayerData(List<Requests> requests) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String ep = requests[0].endpoint;
        String payerEmail = requests[0].payerEmail;
        switch on ep {
            when 'default' {
                request.setEndpoint('callout:MercadoPago_Preapproval_Search_Default/?payer_id=' + requests[0].payerId);
            }
            when 'alternative' {
                request.setEndpoint('callout:MercadoPago_Preapproval_Search_Alternative/?payer_id=' + requests[0].payerId);
            }
        }
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        Results res = new Results();
        if (response.getStatusCode() == 200) {
            Map<String, Object> searchResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            List<Object> mapResults = (List<Object>) searchResponse.get('results');
            Contact c = new Contact(MP_Payer_ID__c = requests[0].payerId);
            Boolean found = false;
            if (mapResults.size() > 0) {
                for (Object mapResult : mapResults) {
                    Map<String, Object> result = (Map<String, Object>) mapResult;
                    String surName = String.ValueOf(result.get('payer_last_name'));
                    c.FirstName = String.ValueOf(result.get('payer_first_name'));
                    if (surName.containsNone('*') && surName.length() > 0) {
                        c.LastName = surName;
                        found = true;
                        break;
                    }
                }
            }
            if (!found && !String.isEmpty(payerEmail)) {
                c.FirstName = '';
                c.LastName = payerEmail;
            } else if (!found) {
                c.LastName = '.';
            }
            res.c = c;
            res.status = true;
        } else {
            res.status = false;
        }
        List<Results> resultList = new List<Results>();
        resultList.add(res);
        return resultList;
    }
    
    private static List<Results> ParsePaymentDates(List<Requests> requests) {
        MP_Payment__c payment = requests[0].payment;
        payment.Card_Date_Created_DT__c = payment.Card_Date_Created__c == null ? null : parseDate(payment.Card_Date_Created__c);
        payment.Card_Date_Last_Updated_DT__c = payment.Card_Date_Last_Updated__c == null ? null : parseDate(payment.Card_Date_Last_Updated__c);
        payment.Date_Approved_DT__c = payment.Date_Approved__c == null ? null : parseDate(payment.Date_Approved__c);
        payment.Date_Created_DT__c = payment.Date_Created__c == null ? null : parseDate(payment.Date_Created__c);
        payment.Date_Last_Updated_DT__c = payment.Date_Last_Updated__c == null ? null : parseDate(payment.Date_Last_Updated__c);
        Results res = new Results();
        res.paymentR = payment;
        res.status = true;
        List<Results> resultList = new List<Results>();
        resultList.add(res);
        return resultList;
    }
    
    private static List<Results> ParseSubscriptionDates(List<Requests> requests) {
        MP_Subscription__c sub = requests[0].subscription;
        sub.MP_Auto_Recurring_End_Date_DT__c= sub.MP_Auto_Recurring_End_Date__c == null ? null : parseDate(sub.MP_Auto_Recurring_End_Date__c);
        sub.MP_Auto_Recurring_Start_Date_DT__c= sub.MP_Auto_Recurring_Start_Date__c == null ? null : parseDate(sub.MP_Auto_Recurring_Start_Date__c);
        sub.MP_Date_Created_DT__c= sub.MP_Date_Created__c == null ? null : parseDate(sub.MP_Date_Created__c);
        sub.MP_Last_Modified_DT__c= sub.MP_Last_Modified__c == null ? null : parseDate(sub.MP_Last_Modified__c);
        sub.MP_Next_Installment_Date_DT__c= sub.MP_Next_Installment_Date__c == null ? null : parseDate(sub.MP_Next_Installment_Date__c).dateGMT();
        sub.MP_Summary_Last_Charged_Date_DT__c = sub.MP_Summary_Last_Charged_Date__c == null ? null : parseDate(sub.MP_Summary_Last_Charged_Date__c);
        Results res = new Results();
        res.subscriptionR = sub;
        res.status = true;
        if (sub.MP_Auto_Recurring_Frequency_Type__c == 'months') {
            res.dayOfMonth = sub.MP_Auto_Recurring_Start_Date_DT__c.day();
        }
        List<Results> resultList = new List<Results>();
        resultList.add(res);
        return resultList;
    }
    
    private static List<Results> ParsePlanDates(List<Requests> requests) {
        MP_Subscription_Plan__c plan = requests[0].plan;
        plan.MP_Date_Created_DT__c = plan.MP_Date_Created__c == null ? null : parseDate(plan.MP_Date_Created__c);
        plan.MP_Last_Modified_DT__c = plan.MP_Last_Modified__c == null ? null : parseDate(plan.MP_Last_Modified__c);
        Results res = new Results();
        res.planR = plan;
        res.status = true;
        List<Results> resultList = new List<Results>();
        resultList.add(res);
        return resultList;
    }
    
    private static Datetime parseDate(String text) {
        String tZmins = text.substring(23,24)+text.substring(27,29);
        Datetime fullDate = Datetime.newInstanceGmt(Integer.valueOf(text.substring(0,4)),Integer.valueOf(text.substring(5,7)),Integer.valueOf(text.substring(8,10)),Integer.valueOf(text.substring(11,13)),Integer.valueOf(text.substring(14,16)),Integer.valueOf(text.substring(17,19)));
        fullDate = fullDate.addHours(-Integer.valueOf(text.substring(23,26)));
        fullDate = fullDate.addMinutes(-Integer.valueOf(tzMins));
        return fullDate;
    }
    
    global class Requests {
        @InvocableVariable 
        global String action;
        @InvocableVariable
        global String payerId;
        @InvocableVariable
        global String endpoint;
        @InvocableVariable
        global String payerEmail;
        @InvocableVariable
        global MP_Payment__c payment;
        @InvocableVariable
        global MP_Subscription__c subscription;
        @InvocableVariable
        global MP_Subscription_Plan__c plan;
    }
    
    global class Results{
        @InvocableVariable
        global Contact c;
        @InvocableVariable
        global boolean status;
        @InvocableVariable
        global MP_Payment__c paymentR;
        @InvocableVariable
        global MP_Subscription__c subscriptionR;
        @InvocableVariable
        global MP_Subscription_Plan__c planR;
        @InvocableVariable
        global Integer dayOfMonth;
    }
}